# Generated by Django 4.0.1 on 2022-02-01 16:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0004_alter_pessoa_email'),
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='pessoa',
            field=models.ForeignKey(default=1, help_text='Pessoa a postar a receita', on_delete=django.db.models.deletion.DO_NOTHING, to='pessoas.pessoa'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.ForeignKey(help_text='Categoria da receira. (Ex: SOPAS|CARNES|SUCOS)', on_delete=django.db.models.deletion.DO_NOTHING, to='receitas.categoria'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='Data de postagem da receita'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='ingredientes',
            field=models.TextField(help_text='Ingredientes utilizados na receita'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='modo_preparo',
            field=models.TextField(help_text='Modo de preparo da receita'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='nome',
            field=models.CharField(help_text='Nome da receita', max_length=200),
        ),
        migrations.AlterField(
            model_name='receita',
            name='rendimento',
            field=models.CharField(help_text='Rendimento da receita. (Ex: 5 porções', max_length=100),
        ),
        migrations.AlterField(
            model_name='receita',
            name='tempo_preparo',
            field=models.IntegerField(help_text='Tempo de preparo da receita em minutos. (Ex: 10 minutos)'),
        ),
    ]
