# Generated by Django 4.0.1 on 2022-01-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_alter_pessoa_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(help_text='Nome do usuário', max_length=255),
        ),
    ]
