# Generated by Django 4.0.1 on 2022-02-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_alter_pessoa_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(help_text='E-mail do usuário (Ex: exemplo@dominio.com', max_length=200),
        ),
    ]
